--1.what is the total revenue generated by male v/s female
select gender ,sum(purchase_amount)as revenue
from customer
group by gender 
--2.which customers used a discount but spent more than the average purchase amount
select customer_id,purchase_amount
from customer
where discount_applied='Yes' and purchase_amount >= (select AVG(purchase_amount)from customer)
--3.which are the top best rated products according to customers
Select item_purchased, round(avg(review_rating::numeric),2) as "Average Ratings"
from customer
group by item_purchased
order by avg(review_rating)desc
limit 10;
--4. Compare the average purchase amount between standard and express shipping
select shipping_type, round(avg (purchase_amount),2) as "average payment" 
from customer
where shipping_type in ('Standard','Express')
group by shipping_type
--5. Do subscribe customer spend more ?compare average spend and total revenue 
--between subscriber and non subscriber
select subscription_status ,
count(customer_id) as total_customers,
round(sum(purchase_amount),2) as "Total amount received",
round(avg (purchase_amount),2) as "average amount"
from customer
group by subscription_status;
--6. which 5 S
select item_purchased,
Round(100 * sum(case when discount_applied='Yes' Then 1 else 0 end)/count(*),2) as discount_rate
from customer 
group by item_purchased
order by discount_rate desc
limit 5;
--7.Segment customer into New ,returnin and loyal based on their total 
--number of previous purchases , and show the count of each segment
with customer_type as (
select customer_id, previous_purchases,
Case
	When previous_purchases =1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer
)
select customer_segment ,count (*) as "No.of Customer"
from customer_type 
group by customer_segment
--8 What are the 3 topmost purchased product within each category
with item_counts as 
(
	select category,
	item_purchased,
	count(customer_id) as total_orders,
	row_number()over(partition by category order by count(customer_id)DESC) as item_rank
	from customer
	group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3;
--Q9 Are customer who are repeat buyers (more than 5 previous purchases) also like to subscribe
select subscription_status,
count (customer_id)as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status
--Q10 what is the revenue contribution of each age group
select * from customer 
select age_group,
sum (purchase_amount) as "total_revenue"
from customer
group by age_group
order by total_revenue desc 